services:

  broker:
    container_name: mqtt_broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./mqtt_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt_broker/password.txt:/mosquitto/config/password.txt
      - ./mqtt_broker/data:/mosquitto/data
      - ./mqtt_broker/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  db:
    container_name: mqtt_db
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - ./mqtt_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  db-view:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
